# Generated by Django 6.0.1 on 2026-01-08 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audits", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investigation_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("incident_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "incident_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("incident_time", models.TimeField(blank=True, null=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("INCIDENT", "Incidente"),
                            ("NEAR_MISS", "Casi incidente"),
                            ("UNSAFE_ACT", "Acto inseguro"),
                            ("UNSAFE_CONDITION", "Condición insegura"),
                            ("OTHER", "Otro"),
                        ],
                        default="INCIDENT",
                        max_length=40,
                    ),
                ),
                (
                    "sector_text",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "task_performed",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "task_mastery",
                    models.CharField(
                        choices=[
                            ("HIGH", "Alto"),
                            ("MEDIUM", "Medio"),
                            ("LOW", "Bajo"),
                            ("UNKNOWN", "No informado"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "operator_sector",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "operator_position",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "operator_seniority",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "responsible_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "responsible_role",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Bajo"),
                            ("MEDIUM", "Medio"),
                            ("HIGH", "Alto"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "cause_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("why_1", models.TextField(blank=True, default="")),
                ("why_2", models.TextField(blank=True, default="")),
                ("why_3", models.TextField(blank=True, default="")),
                ("why_4", models.TextField(blank=True, default="")),
                ("why_5", models.TextField(blank=True, default="")),
                (
                    "legal_framework_internal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("improvement_observation", models.TextField(blank=True, default="")),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="core.sector",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="audits.auditvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-incident_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Acción inmediata"),
                            ("CORRECTIVE", "Acción correctiva"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "owner_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En proceso"),
                            ("DONE", "Cerrada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "execution_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "closure_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "effectiveness_theoretical",
                    models.CharField(
                        choices=[
                            ("HIGH", "Alta"),
                            ("MEDIUM", "Media"),
                            ("LOW", "Baja"),
                            ("NA", "No aplica"),
                        ],
                        default="NA",
                        max_length=10,
                    ),
                ),
                (
                    "effectiveness_practical",
                    models.CharField(
                        choices=[
                            ("HIGH", "Alta"),
                            ("MEDIUM", "Media"),
                            ("LOW", "Baja"),
                            ("NA", "No aplica"),
                        ],
                        default="NA",
                        max_length=10,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["action_type", "status", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="incidents/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="incidents.incident",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["visit", "incident_date"], name="incidents_i_visit_i_f8eb81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["incident_type", "incident_date"],
                name="incidents_i_inciden_24fc56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["risk_level", "incident_date"],
                name="incidents_i_risk_le_95072e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                condition=models.Q(("incident_number__isnull", False)),
                fields=("visit", "incident_number"),
                name="uq_incident_visit_number",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["action_type", "status"], name="incidents_a_action__c1b2a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["status", "closure_date"], name="incidents_a_status_a3547f_idx"
            ),
        ),
    ]
